### ISSUE TITLE
Python Script no longer works since TAPO plugs updated

### ISSUE THREAD

**Issue by netcruiser2k10** [bentasker/tplink_to_influxdb#3]
Hi

The Python scripts does not seem to be collecting the data from plugs since they have updated to 1.3.0 (build 230905 Rel 15220) i have restarted the program in a separate LXC contianer and also check for any updates on the script from git hub. 

Is there any way of running the script with Verbose to see if any error codes come up.

![Screenshot 2023-12-19 203044](https://github.com/bentasker/tplink_to_influxdb/assets/104116318/3a867698-41f8-4450-acfc-908c1cf41294)

This is all it says when i try to run the python script.

**Comment by bentasker** [comment]
Hey,

Sounds like the new firmware has broken something - the script relies on a 3rd party module to speak to the plugs so there isn't much for it to reveal (although adding a verbose option to make it print details of any exceptions is a good shout).

Looking at the upstream tracker, does look like this is a thing: https://github.com/fishbigger/TapoP100/issues/136

The upstream code also seems to have fallen out of maintenance though.

There's [a fork](https://github.com/almottier/TapoP100), though, which claims to support the new firmware - try doing this
```
pip3 install git+https://github.com/almottier/TapoP100.git@main
```

For me, that broke comms with my plugs (because I've long since blocked them from updating) - it looks like the library has support for the old auth method though, so I'll see whether I can get that working

**Comment by bentasker** [comment]
Ah, that's not going to work for you without changes - I've had to [hack at the module](https://github.com/almottier/TapoP100/issues/14) but got it talking to my plugs. The response from `p110.getEnergyUsage()` differs slightly to the original module - with the original, everything was nested under and attribute called `result`, whereas the new module abstracts that away.

I'll need to add some handling for that.

**Comment by bentasker** [comment]
Ok, there's a modified version at https://github.com/bentasker/tplink_to_influxdb/blob/p100-lib-change/app/collect.py

@netcruiser2k10  could you please give that a try and let me know if it works with your plugs?

**Comment by netcruiser2k10** [comment]
Thank you for taking time to respond

I have copied the prompts you listed on the previous response and it throws out a error "Error: {'error_code': 1003}
Failed to initialize protocol OldProtocol..." (See scrrenshot)

![Screenshot 2023-12-21 193453](https://github.com/bentasker/tplink_to_influxdb/assets/104116318/27c1830a-4634-4a36-b7d4-f1e092508c9b)

**Comment by bentasker** [comment]
Thanks for checking. Looks like the beginning of the report at https://github.com/almottier/TapoP100/issues/13

I'll see if I can find a spare plug (or one I don't mind upgrading) to see if I can see what's going on

**Comment by netcruiser2k10** [comment]
Thanks for responding again

yeahhh it does, looks like the firmware update has royally screwed up how the python module communicates to the plugs. By look at the error i saw it said something about handshake errors and to be sure it wasnt my login details within the config file i changed the password and tried that but it still comes up with it. In hindsight i should have either turned off the auto-update or blocked them from communicating witht he internet. 

Ill look forward to seeing if anything can be found with them from your side. No worries though if you havent got a spare plug to sacrifice :) 

Thanks Again

Alistair

**Comment by netcruiser2k10** [comment]
Ive been reading articles about people having issues with plugs and bulbs using the PyP100 module for Home Assistant which have said that something has changed within the protocols that are used with some saying that it could using a KLAP protocol that is changing the way the handshake and encyption is working.

https://github.com/openhab/openhab-addons/issues/15503
https://github.com/openhab/openhab-addons/pull/15725
https://community.openhab.org/t/single-tapo-p100-suddenly-stopped-working-error-code-1003/149740/2

Ill keep looking to see what i can find but hope this helps

**Comment by bentasker** [comment]
Yep - that switch to KLAP is why I updated the library to use the forked version of PyP100 - it's more recently updated and claims to support KLAP.

The error code you're getting is almost like the new library isn't being used (as far as I can make out, it's used to indicate the  plug expected JSON and didn't get any), I wonder if it's being caused by the initial use with `preferred_protocol`.

In the downloaded copy of the script, you should see
```python
    try:
        # Try using the new signature to communicate with an older device
        # if this fails, we'll fall through to using the invocation that works
        # with both libraries and newer devices (if the new library is in use)
        p110 = PyP110.P110(ip, user, passw, preferred_protocol="old")
        # The new library runs handshake/login automatically, so we don't need 
        # to invoke those if we know we're using it
        use_old_proto = True
    except:
        pass
```

Put three apostoprophe's before and after to comment it out:
```python
'''
    try:
        # Try using the new signature to communicate with an older device
        # if this fails, we'll fall through to using the invocation that works
        # with both libraries and newer devices (if the new library is in use)
        p110 = PyP110.P110(ip, user, passw, preferred_protocol="old")
        # The new library runs handshake/login automatically, so we don't need 
        # to invoke those if we know we're using it
        use_old_proto = True
    except:
        pass
'''
```

and see whether it then works for you.

I do have a spare Kasa plug, so tomorrow I'll figure out which Tapo I can best swap it out for so that I've something to test against.

**Comment by netcruiser2k10** [comment]
Hi
Thanks again for responding

I have made the change to the collect.py script you listed above

![Screenshot 2023-12-22 005302](https://github.com/bentasker/tplink_to_influxdb/assets/104116318/47098a29-1e00-4f56-8a35-ccaa28710bf1)

It hasnt made it work im afraid and comes up with a error that is less in length than the first one

![Screenshot 2023-12-22 005317](https://github.com/bentasker/tplink_to_influxdb/assets/104116318/9df33850-53b9-405b-a5df-588b51995071)

Its possible i may have not indented it properly so will do a little experimeting with the indenting of the apostrophoes but i doubt it would make any difference. I have checked the parts above and below to double check non of them have been inadvertedly moved however theyre where they should be. 

Thanks

**Comment by bentasker** [comment]
No worries, thanks for trying.

I've located a Tapo that I don't mind losing if I can't get it working, so I'll try have a tinker with it today.

Given that `python-kasa` has also added (limited) support for some Tapo devices I might also see whether it's possible to switch over to using that - want to try and get PyP100 working first though as that should give a broader support base.

**Comment by bentasker** [comment]
I've got some stuff I need to get done before I can tidy this up enough to commit it, but:
```
ben@optimus:~/Documents/src.old/tplink_smartplug_to_influxdb$ ./app/collect.py 
Using new
Plug: slow-cooker using 0.0W, today: Not Supplied
Wrote 1 points to local
```

Should have a fix for you later today hopefully - at least, once I've figured out the best way to go at it.

When I made the current set of changes, I assumed that the library would fail (or throw an exception) if we tried to use old protocol with a newer plug - we catch that exception and try using the newer method instead.

Except, that's not what happens. It **doesn't** throw an exception, it just accepts it. 

When we call `getEnergyUsage()` the old protocol fails (because new firmware). The library itself does appear to try and failover to using the newer protocol but (for some reason or other) that fails.

If I remove the attempt to use the old protocol entirely it works (though, of course, now won't work with older plugs).

I **think** the way that I'll probably fix this will be either:

- Add support for a config option to denote what auth protocol to use
- Test getting energyusage with the new mode and fall back to old if that fails

In practice, I'll *probably* implement a mix of the two - allow override via config, but test otherwise.

**Comment by bentasker** [comment]
OK, I'm not quite ready to merge it yet (want to see if I can do anything about those hardcoded timeouts first), but if you do the following
```sh
curl https://raw.githubusercontent.com/bentasker/tplink_to_influxdb/p100-lib-change/app/collect.py -o collect.py
chmod +x collect.py

export CONF_FILE="/opt/tapomon/config.yml"
./collect.py
```

you *should* now find that it works.

It functions correctly in my mixed-firmware-version network. 

It should handle it automatically, but if you've got plugs that you know are a specific version you can now force the auth mechanism in the config yaml
```yaml
    devices:
        # Has a version < 1.2.1 
        # and I'm using the forked PyP100
        - 
            name: "big-fridge"
            ip : 192.168.3.153
            auth: "almottier_old"

        # Has a version >= 1.2.1 
        # and I'm using the forked PyP100
        #  Would also be valid if I firmware < 1.2.1
        # and the PyPi module was in use
        -
            name: "slow-cooker"
            ip: 192.168.3.164
            auth: "package_defaults"

        # The default behaviour - try each
        # mechanism in turn
        -
            name: "washing-machine"
            ip: 192.168.3.167
            auth: "all"

```

**Comment by bentasker** [comment]
OK, changes are all now merged.

So, if you force an upgrade of the PyP100 module (to get the timeout change)
```sh
pip3 install --force-reinstall git+https://github.com/almottier/TapoP100.git@main
```

You should be able to fetch and use the main script now
```sh
curl https://github.com/bentasker/tplink_to_influxdb/raw/master/app/collect.py -o collect.py
chmod +x collect.py

export CONF_FILE="/opt/tapomon/config.yml"
./collect.py
```

What I haven't done, yet, is cut the docker image over to using the new module

**Comment by netcruiser2k10** [comment]
Hi Ben

I have implemented the changes as described in the above and through your repository and it no appears to be working as it should be. 
I have set the AUTH setting in the config.yml file to "package_defaults" as i think its the best one to go with for efficiency as all my Tapo Plugs are on the same firmware. Unless you think that it be set to another setting. 

I think for now ill stop my devices from updating automatically just to avoid something like this happening again. 

Thank you for looking in to this and providing a fix and hope that it wasnt too much trouble doing so. :) :)

**Comment by bentasker** [comment]
If all your devices are on the same version (or, more specifically, on >=1.2.1) then `package_defaults` is the right choice, yep.

No real trouble :) I'll probably leave that one device able to update so it can act as a canary

**Comment by netcruiser2k10** [comment]
Ok will do, Think ill do the same with one of my Tapo Plugs just to see if anything changes when theres another firmware update. 

Hope you have a Lovely Christmas and New Year :) :)

**Comment by rick165** [comment]
I'm wondering if anyone can help?. I'm  trying to get the Tapo P100 plugs to turn off/on using the PyP100 module however I cannot get it to work. 
I've reinstalled the module as mentioned above using 
`pip3 install --force-reinstall git+https://github.com/almottier/TapoP100.git@main`

and  then try to run the following code 

```
from PyP100 import PyP100

p100 = PyP100.P100("192.168.2.115", "username@mail.com", "password", preferred_protocol="old") #Creating a P100 plug object

p100.handshake() #Creates the cookies required for further methods

```
using new and old in the preferred_protocol. However I get the following errors.
```

rick@rick-desktop:~/scripts/tapo$ python tapop100.py 
Error: {'error_code': -1501}
Failed to initialize protocol OldProtocol
Traceback (most recent call last):
  File "/home/rick/.local/lib/python3.10/site-packages/PyP100/PyP100.py", line 32, in _initialize
    protocol.Initialize()
  File "/home/rick/.local/lib/python3.10/site-packages/PyP100/auth_protocol.py", line 258, in Initialize
    result = self._request(
  File "/home/rick/.local/lib/python3.10/site-packages/PyP100/auth_protocol.py", line 203, in _request
    raise Exception(f"Error code: {data['error_code']}")
Exception: Error code: -1501
Traceback (most recent call last):
  File "/home/rick/scripts/tapo/tapop100.py", line 6, in <module>
    p100.handshake() #Creates the cookies required for further methods
  File "/home/rick/.local/lib/python3.10/site-packages/PyP100/PyP100.py", line 48, in handshake
    self._initialize()
  File "/home/rick/.local/lib/python3.10/site-packages/PyP100/PyP100.py", line 39, in _initialize
    raise Exception("Failed to initialize protocol")
Exception: Failed to initialize protocol

```
or this when trying 'new'
```

rick@rick-desktop:~/scripts/tapo$ python tapop100.py 
Failed to initialize protocol AuthProtocol
Traceback (most recent call last):
  File "/home/rick/.local/lib/python3.10/site-packages/PyP100/PyP100.py", line 32, in _initialize
    protocol.Initialize()
  File "/home/rick/.local/lib/python3.10/site-packages/PyP100/auth_protocol.py", line 95, in Initialize
    response = self._request_raw("handshake1", local_seed)
  File "/home/rick/.local/lib/python3.10/site-packages/PyP100/auth_protocol.py", line 45, in _request_raw
    resp.raise_for_status()
  File "/home/rick/.local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://192.168.2.115/app/handshake1
Traceback (most recent call last):
  File "/home/rick/scripts/tapo/tapop100.py", line 6, in <module>
    p100.handshake() #Creates the cookies required for further methods
  File "/home/rick/.local/lib/python3.10/site-packages/PyP100/PyP100.py", line 48, in handshake
    self._initialize()
  File "/home/rick/.local/lib/python3.10/site-packages/PyP100/PyP100.py", line 39, in _initialize
    raise Exception("Failed to initialize protocol")
Exception: Failed to initialize protocol

```

The firmware of the plug is 1.4.18

**Comment by bentasker** [comment]
Hey @rick165 

You've probably a better chance of meaningful help by posting in the PyP100 repo than commenting on a closed ticket.

The library isn't very verbose about why it's failed though, the message that you've got basically translates to "I failed to connect or the plug didn't respond in time".

The second traceback suggests that the library connected to the plug OK, but the plug returned a 404:
```
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://192.168.2.115/app/handshake1
```

I've just tried against my test plug and I can get that same thing to happen if I provide incorrect credentials:
```
>>> p100 = PyP100.P100("192.168.3.164", "<redacted>", "<redacted>", preferred_protocol="new")
>>> p100.handshake()
>>> p100 = PyP100.P100("192.168.3.164", "NOTME", "NOTMYPASS", preferred_protocol="new")
>>> p100.handshake()
Failed to initialize protocol AuthProtocol
Traceback (most recent call last):
  File "/home/ben/.local/lib/python3.10/site-packages/PyP100/PyP100.py", line 32, in _initialize
    protocol.Initialize()
  File "/home/ben/.local/lib/python3.10/site-packages/PyP100/auth_protocol.py", line 110, in Initialize
    raise Exception("Failed to authenticate")
Exception: Failed to authenticate
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ben/.local/lib/python3.10/site-packages/PyP100/PyP100.py", line 48, in handshake
    self._initialize()
  File "/home/ben/.local/lib/python3.10/site-packages/PyP100/PyP100.py", line 39, in _initialize
    raise Exception("Failed to initialize protocol")
Exception: Failed to initialize protocol
```

So, it'd be worth checking your credentials are correct. I've a vague recollection of (while I was looking into the original issue) seeing some posts from people that needed to reset their password to get things working.
